### ISSUE TITLE
Moving away from pickle output

### ISSUE THREAD

**Issue by jamcam11** [biomedicalinformaticsgroup/cadmus#3]
The retrieval system was built for moderate-sized corpora (<10k) initially. As corpora have scaled, there is an issue with the speed of reading and writing large data frames into pickle objects. The system becomes very slow and can freeze during these steps. To overcome this, we propose to move to simple text files for storing data for each record. I've created a new branch called "new_output" for working on transfer from pickled output to structured directories of text files for the raw files, retrieved text and metadata.

**Comment by Antoinelfr** [comment]
This has been corrected and we moved away from pickle to a directory with txt files.
